spring:
  application:
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///reggie?useSSL=false
      username: root
      password: root
  main:
    banner-mode: off
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000
#    password: root
server:
  port: 80
#  servlet:
#    session:
#      # Session存活时长（分钟）
#       timeout: 30

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1
    banner: false

reggie:
  dish-images-dir: C:\Users\Xu\IdeaProjects\heima_reggie\src\main\resources\static\backend\images\dish-images\