spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.104:3306/reggie?useSSL=false
        username: root
        password: root
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.103:3306/reggie?useSSL=false
        username: root
        password: root
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true
  application:
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///reggie?useSSL=false
      username: root
      password: root
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  redis:
    host: 192.168.0.104
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000
#    password: root
server:
  port: 8080
#  servlet:
#    session:
#      # Session存活时长（分钟）
#       timeout: 30

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1
    banner: false

reggie:
  dish-images-dir: /usr/local/img/